# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275fc83c8d3dfc732b0c7990d4eebccd591ed3900422100b4ac55583237aeb6bdc52ea3679a9823cb7882278a74f3d41d33c6d87e5b4da2456441aeafe403599

test:
  secret_key_base: a5b4f04a0410a2ec26f6c7cba0c5a03b09ad2ab4197f295bef53cd5ccda23a09f33ced6d9d8502c90dd681b82d116ff066fa85bdc95745523bcb0ffa785cd66c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  publishable_key: ENV['pk_test_0HUzYe6XEREYNHjKtIaliZYo'],
  secret_key:      ENV['sk_test_LwfS8QLROZUhwzsoMBL2Aldx']


#reset keys
